name: Deploy Changed Projects

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Get changed top-level directories
        id: changed-dirs
        run: |
          dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d/ -f1 | sort -u)
          # 디렉토리만 필터링 (파일 제외)
          changed_dirs=""
          for dir in $dirs; do
            if [ -d "$dir" ]; then
              changed_dirs="$changed_dirs $dir"
            fi
          done
          echo "dirs=$changed_dirs" >> $GITHUB_OUTPUT

      - name: Deploy only changed folders
        if: steps.changed-dirs.outputs.dirs != ''
        run: |
          for dir in ${{ steps.changed-dirs.outputs.dirs }}; do
            echo "Deploying $dir"
            cd "$dir"
            npm install
            npm run build
            npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --cwd . --yes
            cd ..
          done